
package proxy;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "BanqueService", targetNamespace = "http://enset.ma/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueService {


    /**
     * 
     * @return
     *     returns java.util.List<proxy.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "compteList", targetNamespace = "http://enset.ma/", className = "proxy.CompteList")
    @ResponseWrapper(localName = "compteListResponse", targetNamespace = "http://enset.ma/", className = "proxy.CompteListResponse")
    @Action(input = "http://enset.ma/BanqueService/compteListRequest", output = "http://enset.ma/BanqueService/compteListResponse")
    public List<Compte> compteList();

    /**
     * 
     * @param code
     * @return
     *     returns proxy.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCompte", targetNamespace = "http://enset.ma/", className = "proxy.GetCompte")
    @ResponseWrapper(localName = "getCompteResponse", targetNamespace = "http://enset.ma/", className = "proxy.GetCompteResponse")
    @Action(input = "http://enset.ma/BanqueService/getCompteRequest", output = "http://enset.ma/BanqueService/getCompteResponse")
    public Compte getCompte(
        @WebParam(name = "code", targetNamespace = "")
        long code);

    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "convertoToEuro", targetNamespace = "http://enset.ma/", className = "proxy.ConvertoToEuro")
    @ResponseWrapper(localName = "convertoToEuroResponse", targetNamespace = "http://enset.ma/", className = "proxy.ConvertoToEuroResponse")
    @Action(input = "http://enset.ma/BanqueService/convertoToEuroRequest", output = "http://enset.ma/BanqueService/convertoToEuroResponse")
    public double convertoToEuro(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0);

}
